### ISSUE TITLE
23.10 Broken Addons List

### ISSUE THREAD

**Issue by shmuelsash** [shigeyukey/my_addons#10]
The Anking has a running list of addons that were broken with the 23.10 update. Perhaps you could help update them?

https://ankingmed.notion.site/322a9c869fa1401894338ca65a565c42?v=30e8eaa080c54d08844577ed6591f399

Thanks for all your work fixing addons!
I'm really enjoying the "Today Again" one 😄

**Comment by shigeyukey** [comment]
Hello, thanks for the feedback and request! 

Most of those add-ons seem to have already been repaired or are partially functional (Anki23+).
I have updated the repair information, please check it out.
* [ Simple Fix Add-ons for the latest Anki (23.12+) by Shige ](https://www.patreon.com/posts/99149368)
