### ISSUE TITLE
[FORVO downloader] Breaks at getting audios

### ISSUE THREAD

**Issue by darlopvil** [shigeyukey/my_addons#24]
Hello,

When adding a word/sentence a pressing the button, this small window appears:
![imagen](https://github.com/shigeyukey/my_addons/assets/60988792/88c3d8a9-e139-4f14-a44b-98f869868633)

This is the Debug info:

`Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

Traceback (most recent call last):
  File "aqt.webview", line 628, in handler
  File "aqt.editor", line 627, in <lambda>
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1784714388\__init__.py", line 220, in <lambda>
    editor.saveNow(lambda: add_pronunciation(editor, mode))
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1784714388\__init__.py", line 131, in add_pronunciation
    results = forvo.get_pronunciations().pronunciations
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1784714388\src\Forvo.py", line 151, in get_pronunciations
    id_, = {
ValueError: too many values to unpack (expected 1)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2024-04-22T10:46, 'None', mod]
Anki Day of Rest ['1776268610', 2023-02-25T20:00, 'None', '']
AnkiConnect ['2055492159', 2024-02-27T05:37, 'None', '']
Editor Live Preview ['1960039667', 2024-03-05T00:59, 'None', '']
Forvo Pronunciation Downloader fully automatic - Fixed for Anki 23 by Shige ['1784714388', 2024-03-01T05:04, 'None', '']
Image Editor ['307397307', 2022-09-08T06:09, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-04-11T12:35, 'None', '']
More Overview Stats ['2116130837', 2024-04-15T20:07, 'None', '']
OpenInExternalEditorRenameDuplicate for ImageAudioVideo ['1560623518', 2023-03-19T18:33, 'None', mod]
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-24T02:59, 'None', '']
RefoldEase ['819023663', 2023-11-03T04:01, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
Simple Forvo Audio Downloader ['560814150', 2023-10-31T17:47, 'None', mod]
Study Time Stats ['1247171202', 2024-02-24T17:59, 'None', '']
True Retention ['613684242', 2017-11-19T21:43, 'None', '']
Yomichan Forvo Server ['580654285', 2023-08-30T22:53, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T16:12, 'None', mod]

===IDs of active AnkiWeb add-ons===
1247171202 1344485230 1556734708 1560623518 1771074083 1776268610 1784714388 1960039667 2055492159 2116130837 307397307 560814150 580654285 613684242 805891399 819023663 876946123

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Wiktionary ['2087444887', 2023-12-07T00:45, 'None', mod]`

I'd like to say that this behavior isn't common, only happens from time to time and I don't do anything unusual in relation to this.

**Comment by shigeyukey** [comment]
Thanks for the error report. Forvo Pronunciation Downloader was repaired by the author on the original add-on (April 28, 2024).
So I have not developed my repaired version recently.

 * Original Add-on : [anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ](https://ankiweb.net/shared/info/858591644)

Are you encountering that problem with the original Add-on as well?

**Comment by shigeyukey** [comment]
Perhaps the original add-on is already available, so this add-on is out of development. If the error has not been resolved, please contact me again. Thank you.

**Comment by darlopvil** [comment]
Hello,

sorry for the delay. I've just checked the OG version and it fails at presenting all the recordings for an entry. Made an issue there btw, hope the creator sees it.

Regarding your addon, I'll use it until it breaks again or whatever. Funny thing, it hasn't shown this bug since I mentioned it here.

Greetings.

**Comment by shigeyukey** [comment]
Thanks for the feedback.
Hmmm, in that case I will keep this add-on in place and not delete it.
I'll look into the cause later when I have more time.
