### ISSUE TITLE
Pokemanki Startup Issue

### ISSUE THREAD

**Issue by brooktrout1** [shigeyukey/my_addons#26]
Recently downloaded Add-on, but it would not start and threw this issue. Any help would be greatly appreciated!

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.4.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/katie/Library/Application Support/Anki2/addons21/1677779223/main.py", line 193, in replace_gears
    tr.select("img.gears")[0]["src"] = f"{pkmnimgfolder}/{name}.webp"
IndexError: list index out of range

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2024-02-04T13:38, 'None', '']
Anki Terminator - ChatGPT Sidebar for Review GoogleGemini Created by Shige ['1428126516', 2024-06-04T23:06, 'None', mod]
Anki X Markdown X MindMap ['728482867', 2022-07-09T00:07, 'None', '']
AnkiCollab - The free collaboration Platform ['1957538407', 2024-05-19T15:43, 'None', mod]
AnkiConnect ['2055492159', 2024-02-26T23:37, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T11:07, 'None', '']
Beautify-Anki 20 mizmu ['1116770498', 2023-10-31T14:51, 'None', mod]
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-05-21T00:19, 'None', '']
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Google Doc Decks Remote Decks ['924929499', 2024-05-04T21:58, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-06-01T10:02, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Kindle Highlights Importer ['1844303519', 2023-07-16T17:23, 'None', '']
Media Import 2 ['129299120', 2024-01-24T08:08, 'None', '']
Multi Deck Importer Fixed by Shige ['1563006742', 2024-02-16T19:33, 'None', '']
Pokemanki Gold - Raising Pokemon with Anki Forked by Shige ['1677779223', 2024-05-01T21:31, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog - Qt6 port ['572933442', 2024-04-02T13:18, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T06:24, 'None', '']
Spreadsheet Import Plus ['716643677', 2022-01-19T13:28, 'None', '']
True Retention ['613684242', 2017-11-19T15:43, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T14:28, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 111623432 1116770498 1136455830 129299120 1374772155 1428126516 1563006742 1677779223 1771074083 1844303519 1908235722 1957538407 2055492159 46611790 572933442 594329229 613684242 716643677 728482867 759844606 864545277 874215009 924929499

**Comment by shigeyukey** [comment]
Thank you for the error report, I will update it later.

**Comment by shigeyukey** [comment]
Maybe it was repaired. If the problem still exists, please contact me again.
