### ISSUE TITLE
[Pokemanki BUG] Fail to trade a pokemon with everstone

### ISSUE THREAD

**Issue by Yisaii** [shigeyukey/my_addons#33]
As mentioned in the title, it is unable to trade a pokemon with everstone, which is given in one previous version. 
After clicking the trade button, a popup will tell that the action is taken successfully but actually not. The name and image of the pokemon suppsed to be traded remain the same. And when I try to take the everstone away, the name of the pokemon with the everstone sometimes changes to the new pokemon supposed to be trade in. Even so, the action of removing the everstone never works actually. The torturing loop continues.  
And all of this stays the same even after I update to the newest version.

**See the debug info. of the failure to remove the everstone:**
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19041

Traceback (most recent call last):
  File "C:\Users\J's\AppData\Roaming\Anki2\addons21\1677779223\pokemon.py", line 340, in takeEverstone
    everstonepokemonlist.remove(textlist[0])
ValueError: list.remove(x): x not in list

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T22:34, 'None', '']
Batch Editing ['291119185', 2023-10-26T08:38, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T18:18, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T23:06, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-04-16T06:11, 'None', mod]
Pokemanki Gold - Raising Pokemon with Anki Forked by Shige ['1677779223', 2024-06-23T15:04, 'None', mod]
export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2024-03-28T21:16, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T22:12, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 1677779223 1967530655 2494384865 291119185 594329229 805891399 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiPA - Pronunciation Assessment for Anki ['86363097', 2024-02-13T06:52, 'None', '']
Fill the blanks - Multiple typecloze support ['1933645497', 2023-05-04T02:21, 'None', '']

**Comment by shigeyukey** [comment]
Thanks for reporting the issue, I'll look into it again.

**Comment by Yisaii** [comment]
Thansk for your attention. And there is somethig to be updated:
Try remove the everstone again and it works. However, the chaos still exists. 
When I get into the DECK, I can see the animation of the new pokemon (the one I made a trade action the previous day to trade in). However, the name and image in the STATS page remains the previous ones, and what is more interesting, it even changes in accordance with the action of removing the everstone (i.e. to become the evolved pokemon).

BTW, hope to make an enquirement. Can I reset the pokemon of one of the decks ? If not, I would like to propose an improvement issue :). And after reseting, are we supposed to lose the levels and experience, or get totally new pokemons ?

**Comment by shigeyukey** [comment]
The Pokemon in the deck are not updated very quickly, so it may take some time.

You can reset the decks.
* Tools -> Pokemanki -> Reset

Perhaps the level and experience should not be lost, the Pokemon's level is calculated by the learning status of the decks.

**Comment by shigeyukey** [comment]
I fixed the Everstone bug.
If the problem continues to occur please contact me again.
