### ISSUE TITLE
Anki Leaderboard

### ISSUE THREAD

**Issue by Renanrois** [shigeyukey/my_addons#35]
Initially, my sincere thanks for your work. I believe my user might be experiencing some bug. Since yesterday, I haven't been appearing in any ranking, whether global, Brazil, or group... I've logged out and logged back in, closed and opened, synchronized, but nothing works... my username is: roisrenan

**Comment by shigeyukey** [comment]
Hello, thanks for reporting the problem.
The database looks fine.
If you update the add-on to the latest version and restart Anki, does the problem continue to occur?

**Comment by Renanrois** [comment]
Hi, Shige. I managed to solve the problem by uninstalling the addon and then adding again. Thanks for the support!

**Comment by shigeyukey** [comment]
Thanks! :-)
