### ISSUE TITLE
🏆️Anki Leaderboard : 'Sync Error' when logged in from 2 PCs

### ISSUE THREAD

**Issue by Foxy-null** [shigeyukey/my_addons#51]
## To reproduce
1. Log in on a first PC
2. Log in on a second PC
3. Try to open Leaderboard on the first PC
4. See the error on the first PC

## Environment
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

<details>
<summary>===Add-ons (active)===</summary>

(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Media Converter  WebP AVIF ['1151815987', 2024-09-18T04:33, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T23:34, 'None', '']
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-09-16T03:18, 'None', mod]
AnkiCraft ['AnkiCraft_file', 2024-03-02T13:12, 'None', mod]
AnkiRestart - Quick Aniki Rebooter for Customize  Develop Created by Shige ['237169833', 2024-09-17T12:13, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-28T04:26, 'None', '']
Ankicord - Discord Rich Presence ['1828536813', 2023-08-17T00:53, 'None', mod]
Audiovisual Feedback ['231569866', 2023-07-09T12:34, '0.8', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-09-14T15:04, 'None', '']
Change Interface Font ['1431333984', 2024-03-08T03:31, 'None', mod]
Contanki - Controller Support for Anki beta ['1898790263', 2024-03-01T10:22, 'v1.0.2', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-09-21T21:33, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T20:47, 'None', '']
Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T16:15, 'None', '']
Incremental Reading v4119 unofficial clone ['999215520', 2023-11-23T02:54, 'None', '']
Leech Toolkit - Advanced tools for handling leech Fixed for Anki 23 by Shige ['1633380637', 2024-02-21T16:33, 'None', '']
Life Drain ['715575551', 2024-04-30T16:15, 'None', mod]
More Decks Stats and Time Left ['1556734708', 2024-08-20T07:49, 'None', mod]
No Distractions Full Screen Fixed by Shige ['1370336700', 2024-08-26T14:08, 'None', mod]
Progress bar for Anki by Shige ['Progress bar for Anki by Shige', 0, 'None', mod]
ReColor ['688199788', 2024-03-03T10:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T10:43, 'None', '']
Review Pass Rate Bar ['1821339370', 2021-09-21T08:41, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T20:24, 'None', '']
Study Time Stats ['1247171202', 2024-02-25T01:59, 'None', '']
SwiftAnki Quick Anki Navigation with Keyboard Shortcuts ['1467361433', 2024-09-14T06:38, 'None', '']
Toggle front and back card in Anki 21 ['1240106570', 2019-07-21T22:19, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T23:12, 'None', mod]
right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2023-05-24T17:59, 'None', mod]

===IDs of active AnkiWeb add-ons===
1046608507 1151815987 1240106570 1247171202 1370336700 1374772155 1431333984 1436550454 1467361433 1556734708 1633380637 175794613 1771074083 1821339370 1828536813 1898790263 231569866 237169833 31746032 46611790 688199788 715575551 759844606 805891399 850294128 874215009 999215520

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['Pop-up dictionary', 0, 'None', mod]
Advanced Answer Sounds ['1167194350', 2024-08-10T16:32, 'None', mod]
Anki Excel Sync ['1832015432', 2021-01-28T12:53, 'None', mod]
Anki Simulator ['817108664', 2023-11-07T02:26, 'None', '']
AnkiCollab - The free collaboration Platform ['1957538407', 2024-09-21T05:51, 'None', mod]
AnkiConnect ['2055492159', 2024-07-26T13:55, 'None', '']
AnkiDraw - Draw and write using mouse and stylus with pressure support ['1868980340', 2024-07-18T07:14, 'None', '']
AnkiOCR ['450181164', 2021-09-19T14:56, 'None', mod]
Ankimon ['1908235722', 0, 'None', mod]
Audio Playback Controls ['312734862', 2023-04-23T08:25, 'None', mod]
Auto Sync ['501542723', 2023-11-21T01:14, 'None', '']
Chunk ProgressBar by Shige ['Chunk ProgressBar by Shige', 0, 'None', mod]
Color Confirmation ['1084228676', 2024-01-06T18:55, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T10:19, 'None', mod]
Duolingo-style gamification -- visual audio and haptic feedback ['255048658', 2024-03-04T03:28, 'None', '']
EaseScouter ['EaseScouter', 0, 'None', '']
Enhance main window ['877182321', 2023-10-23T05:28, 'None', mod]
Pokemanki Gold - Raising Pokemon with Anki Forked by Shige ['1677779223', 2024-06-23T16:04, 'None', '']
PomoTimer - pomodoro timer for Anki Created by Shige ['PomoTimer - pomodoro timer for Anki Created by Shige', 0, 'None', mod]
Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2023-10-02T17:05, 'None', mod]
ProgressBarTimeLeft ['ProgressBarTimeLeft', 0, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-20T06:32, 'None', mod]
Top toolbar icons by Shige ['Top toolbar icons by Shige', 0, 'None', '']

</details>

<details>
  <summary>meta.json (authToken is not included)</summary>

  ```json
  {
      "name": "Anki Leaderboard - Compete with friends to boost motivation Fork by Shige",
      "homepage": "https://www.patreon.com/Shigeyuki",
      "conflicts": [
          "41708974"
      ],
      "mod": 1726424318,
      "min_point_version": 1,
      "max_point_version": 240603,
      "branch_index": 0,
      "disabled": false,
      "config": {
          "username": "Foxy_null",
          "friends": [
              "Foxy_null"
          ],
          "newday": 4,
          "current_group": null,
          "groups": [],
          "country": "Japan",
          "scroll": true,
          "tab": 0,
          "authToken": "(hidden)",
          "achievement": true,
          "sortby": "Cards",
          "hidden_users": [],
          "homescreen": true,
          "autosync": true,
          "maxUsers": 5,
          "focus_on_user": true,
          "import_error": true,
          "show_medals": true,
          "notification_id": null,
          "homescreen_data": [],
          "medal_users": [
              [
                  "Roger CSX",
                  1,
                  0,
                  0
              ],
              [
                  "Bakabear",
                  0,
                  1,
                  0
              ],
              [
                  "domdomday",
                  0,
                  0,
                  2
              ],
              [
                  "jonysina",
                  1,
                  1,
                  0
              ],
              [
                  "snh1212",
                  0,
                  0,
                  2
              ],
              [
                  "Aces_Rodriguez",
                  0,
                  0,
                  1
              ],
              [
                  "kiyotaka",
                  0,
                  0,
                  1
              ],
              [
                  "mishsanat",
                  0,
                  1,
                  1
              ],
              [
                  "BigFatRat",
                  1,
                  1,
                  0
              ],
              [
                  "Davidgoggins",
                  0,
                  1,
                  1
              ],
              [
                  "Tambopata",
                  0,
                  1,
                  0
              ],
              [
                  "Paru",
                  0,
                  1,
                  0
              ],
              [
                  "V22 Osprey",
                  1,
                  0,
                  0
              ],
              [
                  "Der_Ismaelit",
                  3,
                  0,
                  0
              ],
              [
                  "hamdulilah",
                  1,
                  0,
                  0
              ],
              [
                  "BecomingAtlas",
                  1,
                  0,
                  0
              ],
              [
                  "T-",
                  1,
                  0,
                  0
              ],
              [
                  "annevaneyvolley",
                  0,
                  0,
                  1
              ],
              [
                  "sanat",
                  0,
                  1,
                  0
              ],
              [
                  "LiebesLieschen",
                  0,
                  1,
                  0
              ]
          ],
          "shige_chang_log_day": "2024-08-30+",
          "show_home_buttons": true
      },
      "update_enabled": true
  }
  ```
</details>

## Additional context
I suspect it's an authToken issue since the 'authToken' is different on the two PCs.
As a temporary solution, I got it working by copying the authToken from the second PC to the first.

## Screenshot

![image](https://github.com/user-attachments/assets/34696cdb-bf6f-44d6-a732-0035ec1800bc)

**Comment by shigeyukey** [comment]
Thanks for reporting the problem. This problem seems to have been around since the original leaderboard, the author did not fix it because it is rare to use more than two laptops. As you say the workaround is to copy the meta.json directly. It would be useful to be able to do that automatically so I will look into it later.

**Comment by shigeyukey** [comment]
I added a workaround option for this issue and updated it, try the following steps:

[1] Save data to AnkiWeb from your login device: Config -> Others tab -> Sync multiple devices -> Auto save this device's config dat to AnkiWeb[ON]
[2] Sync Anki decks.
[3] Sync Anki's deck on the second device.
[4] Download the config data on the second device: Sync multiple devices -> Download Config data from AnkiWeb

This saved data has nothing to do with the server's leaderboard data, so you can either delete it or not after a successful login. (Sync multiple devices -> Delete AnkiWeb config data)

AnkiWebにパスワードとトークンを保存するとセキュリティが若干心配ですが､add-onはもともとセキュリティが全然なさそうな気がする(たぶん外のadd-onからmeta.jsonに簡単にアクセスできます)んで､まぁいいかなって感じです｡
