### ISSUE TITLE
[Pokemanki] Repetition of hatching info of an egg

### ISSUE THREAD

**Issue by Yisaii** [shigeyukey/my_addons#53]
I have updated to the newest version and I'm very glad the problem of everstone has been fixed. I gave an everstone to my egg, then it hatched to a new pokemon and the stone seems work. 
The problem is, after that, everytime the data of decks refreshes (e.g. open Anki; back to the main page of Decks, etc.), there will be un pop-up telling that a new pokemon is hatched, again and again. There is also a crush of Anki which has forced me to redownload and reinstall the software, otherwise it would be constantly stuck to the opening page.

I have no idea if all these performances are associated with the update or everstone or not. Just let you know about the issue.

**Comment by shigeyukey** [comment]
Hello, thanks for reporting the problem.

>  I gave an everstone to my egg, then it hatched to a new pokemon and the stone seems work.

The egg hatching seems to be a bug. ( it is normal for Pokemon not to hatch until they are level 5 or higher)
Please wait until the Pokemon hatch and then try giving it an Everstone.

> There is also a crush of Anki which has forced me to redownload and reinstall the software, otherwise it would be constantly stuck to the opening page.

I could not reproduce this problem.
If the same problem occurs again, hold down the Shift key to start Anki (All add-ons will be disabled) and toggle off Pokemanki.
 * Tools -> Add-ons -> Select Pokemanki -> Toggle Enable

**Comment by Yisaii** [comment]
Thanks for your attention. 
The Pokemon referred hatched autually at **level 3**. Hope the info may help.
Looking forward to the next update cause the pop-ups show up repetitiously are a little bit annoying lol

**Comment by shigeyukey** [comment]
> The Pokemon referred hatched autually at level 3

Hmmm that's strange, if you take the Everstone won't the Pokemon turn back into the egg?

**Comment by Yisaii** [comment]
> > The Pokemon referred hatched autually at level 3
> 
> Hmmm that's strange, if you take the Everstone won't the Pokemon turn back into the egg?

Genius ! I tried. Yes it does lol. Seems to be a bug of egg hatching triggered by everstone. I'll see if anything abnormal will happen on condition of natural hatching.
