### ISSUE TITLE
Trigger and actions possbile fix

### ISSUE THREAD

**Issue by SolidAlloy** [shigeyukey/my_addons#8]
Hi, thanks for fixing the add-ons!

This post suggests a fix for the "Trigger and actions" plugin which currently doesn't apply triggers automatically.

I made a hack that works alright for my case, but you may want to expand on this and apply full fixes in all the places where hooks are currently broken.

I added the following lines to the end of main.py:
``` python
from aqt import gui_hooks
gui_hooks.sync_did_finish.append(updateAll)
```

There is a hooks API for Anki, and it seems the plugin still tries to use the old hook API.
All the hooks are listed here: https://github.com/ankitects/anki/blob/main/qt/tools/genhooks_gui.py

I made it so that the rules are applied after the sync, I don't need more frequent rules application. You may want to find hooks that will apply rules on save and support config options.

**Comment by shigeyukey** [comment]
Thank you very much! :-)
