### ISSUE TITLE
Customizing the text displayed on mouseover doesn't work

### ISSUE THREAD

**Issue by yuansenvv** [shigeyukey/my_addons#80]
Even if the text is replaced, the original content is still displayed

**Comment by shigeyukey** [comment]
Thanks for the report, what is the name of the add-on that is causing the problem?

**Comment by yuansenvv** [comment]
Enhance main window
![1](https://github.com/user-attachments/assets/826099ea-11b5-4cf3-92ae-14fc6297a1a3)

**Comment by yuansenvv** [comment]
![Uploading 2.png…]()

**Comment by yuansenvv** [comment]
![2](https://github.com/user-attachments/assets/5f2301d9-12a4-4765-8c2b-2d3eec4e312f)

**Comment by shigeyukey** [comment]
Thanks for the screenshot. I fixed it and uploaded it, please try to update the add-on: Tools -> add-ons ->  Check for Updates

**Comment by yuansenvv** [comment]
That's ok, thank you

**Comment by yuansenvv** [comment]
Thanks
