### ISSUE TITLE
[AnkiRestart] It loads a blank profile/acts like a new installation if you have Anki installed anywhere other than the default directory.

### ISSUE THREAD

**Issue by Tenome** [shigeyukey/my_addons#84]
Nevermind, I'm stupid. There's an option in the settings for it.

I have Anki on my D drive, but here it's checking for the default installation directory (`C:\Users\NAME\AppData\Roaming\Anki2\User 1\`). Anyway to change that?

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19044

![User_1_-_Anki 1732314635](https://github.com/user-attachments/assets/5d33ccae-031d-4289-8021-d263ad6c7ff4)

**Comment by shigeyukey** [comment]
Thanks! :-)
