### ISSUE TITLE
🏆️Anki Leaderboard Plus : Divide the next rivals displayed in Chase Mode into multiples of `n`

### ISSUE THREAD

**Issue by Foxy-null** [shigeyukey/my_addons#86]
## Ideal behaviour

Divide the ranking user to every `n`th user, and show the user next to my place as a rival.

## Sample images

-   If I set the value to "10"
    ![image](https://github.com/user-attachments/assets/df2d511f-0d95-44e3-825a-eb115fca2852)
    ![image](https://github.com/user-attachments/assets/b16a7bc2-5070-453a-9cda-c5b9ca6dd6c7)

## Additional Context

Here is a snippet of the PyQt6 frontend code. I wrote this lightly for reference.

### diff for `AnkiLeaderBoardPlus\shige_config\my_addon_config.py` file

![image](https://github.com/user-attachments/assets/acb32a09-8127-400c-bb90-916b5e8b58c6)

<details>

<summary>Click to expand the code</summary>

```python
        self.input_field = QLineEdit()
        self.input_field.setPlaceholderText('倍数nを入力してください')
```

```python
        option_01_layout.addWidget(QLabel("次のライバルを倍数nごとに表示"))

        option_01_layout.addWidget(self.input_field)
```

</details>

**Comment by Foxy-null** [comment]
By the way, I really like the way Leaderboard Plus works.
（お体に気をつけて開発なさってください！応援しています！）

**Comment by shigeyukey** [comment]
お気遣いどうもです! That is an interesting idea, I'll look into it.
This add-on idea was inspired by Kill Streaks and Anki with friends👍️

**Comment by Foxy-null** [comment]
I implemented only the calculation part in my free time.

The only thing left to do is to assign `filter_by_n` as positive integer in the configuration window (maybe).

## Demo

(I set `filter_by_n` to 10 in `meta.json`)

![image](https://github.com/user-attachments/assets/6155180f-3fa0-4288-94de-90bcb93ae61a)

## `calculate_leaderbord.py`

<details>

<summary>Detail changes</summary>

```python
        filter_by_n = max(0, self.config.get("filter_by_n"))

```

```python
                if filter_by_n == 0:
                    start_index = max(0, self_username_index - 1)
                    end_index = self_username_index + 1
                    items = items[start_index:end_index]
                else:
                    # 1. self_username_indexより小さい最も近いnの倍数を計算
                    closest_multiple_of_10 = (self_username_index // filter_by_n) * filter_by_n - 1

                    # 2. インデックス範囲を計算
                    start_index = max(0, closest_multiple_of_10)
                    end_index = min(len(items), self_username_index + 1)

                    # 3. リスト内の間を除外して調整
                    # 必要な要素だけ抽出（startとendの両端のみ残す）
                    if end_index - start_index > 2:
                        items = [items[start_index], items[self_username_index]]
                    else:
                        items = items[start_index:end_index]
```

</details>

![image](https://github.com/user-attachments/assets/1241ff7c-c9a8-4052-8d66-f2fb55166e8a)

## Debug

### `filter_by_n` value

-   [x] -1209385192038572936
    -   → converts to 0
-   [x] 0
    -   → Filter ignored
-   [x] 110293592635091823750192537
    -   → Shows the first place user
-   [x] 1
    -   → Works normally

> [!Note]
> Returns an error if not an `int` type (ex: `0.25` or `"hello"`)

### Combination with other settings

-   [x] Battle Mode
    -   → Filter ignored

**Comment by shigeyukey** [comment]
Wow thank you very much! I will look into that and add it later.

**Comment by Foxy-null** [comment]
Edit: Added a default value of `filter_by_n`
![image](https://github.com/user-attachments/assets/79ee17dd-d82f-47a6-8316-3bca552e290e)

**Comment by shigeyukey** [comment]
* I incorporated this feature and new options, thank you! :-)

* I have invited you to the LeaderboardPlus private repository so feel free to access the latest version anytime. (I have incorporated this feature and option in v2.2.ankiaddon)

**Comment by Foxy-null** [comment]
**Oh my gosh** thank you so much 🥺
