### ISSUE TITLE
Progress bar (Fixed for Anki 24) 04-06 updated version has unknown problem.

### ISSUE THREAD

**Issue by IceTea233** [shigeyukey/my_addons#9]
When I accept the update for this version, everything is fine except the appearance of the toolbar became a little strange.
But when I submit the comments as the pop out coming after the update, everything concerning the configuration of this add-on lead to  error reports.

Here's the error message. Hope it would help you figure out the problem. Thank you a lot!

---

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1708250053\shige_config\progressbar_config.py", line 539, in SetProgressbarConfig
    font_viewer = Shige_Addon_Config()
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1708250053\shige_config\progressbar_config.py", line 70, in __init__
    self.maxWidth = int(config["maxWidth"]) # "20"
ValueError: invalid literal for int() with base 10: '5px'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiWebView Inspector ['31746032', 2023-06-28T03:26, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-02-09T14:42, 'None', '']
CTRLF5 to Refresh the Browser ['1347728560', 2019-07-30T14:36, 'None', '']
Japanese Support ['3918629684', 2023-10-19T11:13, 'None', '']
Progress bar Fixed for Anki 24 by Shige ['1708250053', 2024-04-06T14:43, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1347728560 1436550454 1708250053 1771074083 31746032 3918629684

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['Beautify-Anki', 0, 'None', mod]
Progress Bar original ['1685464019', 2022-07-28T13:24, 'None', mod]

**Comment by shigeyukey** [comment]
Thanks for the error report, I fixed and uploaded it.
